function [out] = T2_blochSim_addEmpty()
% Build an empty sequence (as a starting point).

out = struct(...
    'tp_s',[0],...
    'b1_Hz',[0],...
    'grad',0,...
    'spoil',false,...
    'readout',false);
